### PR TITLE
Deprecate RoR 4.1

### PR DESCRIPTION
**Pull request by pkubatrh**

### CODE REVIEW

**Comment by pvalena** [comment]
@bparees, FYI.

**Comment by pvalena** [comment]
Well, as this is not really used in OpenShift...

**Comment by pkubatrh** [comment]
The deprecated images should already be deprecated in Openshift anyway. At least all of the imagestreams I checked (in sclorg repos) have been set to `hidden`

**Comment by bparees** [comment]
we've never had an imagestream for this ROR image, so this shouldn't be a problem.

**Pull request merged**
