### PR TITLE
Add Ruby on Rails 5.0 Dockerfiles

### PR DESCRIPTION
**Pull request by hhorak**
This will add Dockerfiles for Ruby on Rails 5.0, but since we don't have the packages available in the CentOS repos, we cannot run the tests for this version, so Makefile must not be adjusted at this point. We can IMO merge this PR, and Makefile will be fixed once packages are available (#15).

### CODE REVIEW

**Comment by omron93** [comment]
There are some changes is tests, why not to update older releases too?

```
# Check Rails welcome page
-CONTAINER_ARGS="bash -c 'rails new myapp --skip-bundle && cd myapp && sed -i -e \"s/\(gem.*web-console\)/#\1/\" Gemfile && bundle --local && rails s -b 0.0.0.0 -p 8080'"
+CONTAINER_ARGS="bash -c 'rails new myapp --skip-bundle && cd myapp && bundle && rails s -b 0.0.0.0 -p 8080'"
 run "create_container test_welcome_page"
 CONTAINER_ARGS=
-for i in `seq 10`; do
-    sleep 5
-    run "curl $(get_container_ip 'test_welcome_page'):8080 > output"
-    res=$?
-    run "fgrep 'Ruby on Rails: Welcome aboard' output"
-    test $res = 0 && break
+is_found_welcome_page=0
+for i in `seq 20`; do
+  sleep 10
+  welcome_url="$(get_container_ip 'test_welcome_page'):8080"
+  echo "Connecting ${welcome_url} [${i}]"
+  curl "${welcome_url}" > output
+  fgrep -q '<h1>Yay! You&rsquo;re on Rails!</h1>' output
+  if [ "$?" = 0 ]; then
+    is_found_welcome_page=1
+    break
+  fi
 done
+run "test ${is_found_welcome_page} = 1"
 rm_container test_welcome_page
 
 # Check asset precompilation works
-CONTAINER_ARGS="bash -c 'rails new myapp --skip-bundle && cd myapp && sed -i -e \"s/\(gem.*web-console\)/#\1/\" Gemfile && bundle --local && rake assets:precompile'"
+CONTAINER_ARGS="bash -c 'rails new myapp --skip-bundle && cd myapp && bundle && rake assets:precompile'"
 run "docker run --rm $IMAGE_NAME $CONTAINER_ARGS"
```

**Comment by pkubatrh** [comment]
@omron93 That looks like a change in ror's default splash screen.

**Comment by omron93** [comment]
>That looks like a change in ror's default splash screen.

Yes, the string. But I thought also the way how it is tested...

**Comment by hhorak** [comment]
Thanks for pointing to that, I've just fixed that (4.1 and 4.2 will be fixed same as 5.0 is)

**Comment by omron93** [comment]
Thanks.

**Pull request merged**
